{{- $serviceAccount := "prometheus-instance" }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $serviceAccount }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: sd-discovery
rules:
  - apiGroups: [""]
    resources:
      - pods
      - services
      - endpoints
    verbs:
      - get
      - list
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: sd-discovery-binding
subjects:
  - kind: ServiceAccount
    name: {{ $serviceAccount }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: sd-discovery
  apiGroup: rbac.authorization.k8s.io

