{{- $root := . }}
{{- if .Capabilities.APIVersions.Has "monitoring.coreos.com/v1" }}
{{- range .Values.global.projectLabels }}
{{- range $project, $labels := . }}
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: servicemonitor-{{ $project }}
  labels:
    {{- $labels | toYaml | nindent 4 }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: prometheus-node-exporter
      {{- $labels | toYaml | nindent 6 }}
  namespaceSelector:
    matchNames:
      - {{ $root.Release.Namespace }}
  endpoints:
    - port: http-metrics
      relabelings:
        - targetLabel: job
          replacement: node-exporter
        - targetLabel: cluster
          replacement: kalavai
  sampleLimit: 5000
{{- end }}
{{- end }}
{{- end }}
