{{- $root := . }}
{{- range .Values.global.projectLabels }}
{{- range $project, $labels := . }}
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/scrape: "true"
  labels:
    app.kubernetes.io/name: prometheus-node-exporter
    {{- $labels | toYaml | nindent 4 }}
  name: {{ .Release.Name }}-prometheus-node-exporter-{{ $project }}
spec:
  ports:
    - name: http-metrics
      port: 9100
      protocol: TCP
      targetPort: 9100
  selector:
    app.kubernetes.io/instance: {{ $root.Release.Name }}
    app.kubernetes.io/name: prometheus-node-exporter
    {{- $labels | toYaml | nindent 4 }}
  sessionAffinity: None
  type: ClusterIP
{{- end }}
{{- end }}
