postgres:
  replicas: 2
  db_user: ps_user
  db_password: ps_password
  db_name: ps_name
  storage_class:
    storage_class_name: longhorn-rwx
    storage_size: 10Gi
  service:
    node_port: 30555
  
redis:
  replicas: 2
  service:
    node_port: 30666

litellm:
  general_settings:
    master_key: sk-1234
    salt_key: sk-1234567890
    database_url: postgres-litellm-do-user-14127040-0.l.db.ondigitalocean.com
    database_port: 25060
    database_user: doadmin
    database_password: default
    database_name: defaultdb
    database_connection_pool_limit: 0
    database_connection_timeout: 0
    allow_requests_on_db_unavailable: true
  service:
    node_port: 30777
  