imageTag: latest

deployment:
  nodeSelector: null
  inCluster: "True"
  kalavaiUsernameKey: "kalavai.cluster.user"
  replicas: 1
  useAuthKey: "True"
  adminKey: "somerandomkey"
  readonlyKey: "anotherkey"
  writeKey: "anotherkey2"
  isSharedPool: "True"
  staticWorkspace: null
  kalavaiApiEndpoint: "https://platform.kalavai.net/_/api"
  prometheusEndpoint: "http://thanos-query-frontend.monitoring:9090"
  opencostEndpoint: "opencost.opencost.svc.cluster.local:9003"
  longhornManagerEndpoint: "longhorn-backend.kalavai.svc.cluster.local:9500"

labels: null

service:
  type: NodePort
  nodePort: null

resources:
  requests:
    cpus: 1
    memory: 768Mi
  limits:
    cpus: 2
    memory: 1Gi
    