imageTag: latest

deployment:
  nodeSelector: null
  inCluster: "True"
  kalavaiUsernameKey: "kalavai.cluster.user"
  replicas: 1
  useAuthKey: "True"
  adminKey: "somerandomkey"
  readonlyKey: "anotherkey"
  writeKey: "anotherkey2"
  isSharedPool: "True"
  staticWorkspace: null
  kalavaiApiEndpoint: "https://platform.kalavai.net/_/api"
  prometheusEndpoint: "prometheus-server.prometheus-system.svc.cluster.local:80"
  opencostEndpoint: "opencost.opencost.svc.cluster.local:9003"
  longhorn_manager_endpoint: "longhorn-backend.kalavai.svc.cluster.local:9500"

labels: null

service:
  type: NodePort
  nodePort: null

resources:
  requests:
    cpus: 0.5
    memory: 256Mi
  limits:
    cpus: 1
    memory: 512Mi
    