apiVersion: v1
kind: ConfigMap
metadata:
  name: litellm-config-file
  namespace: {{ .Release.Namespace }}
data:
  config.yaml: |
    cache: false
    cache_params:
      type: redis
      host: "localhost"
      port: 6379 
      password: "your_password"
      namespace: "litellm.caching.caching"
    litellm_settings:
      num_retries: 3
    general_settings:
      master_key: {{ .Values.litellm.general_settings.master_key }}
      database_url: "postgresql://{{ .Values.postgres.db_user }}:{{ .Values.postgres.db_password }}@postgres.{{ .Release.Namespace }}.svc.cluster.local:5432/{{ .Values.postgres.db_name }}"
      disable_prisma_schema_update: false
      database_connection_pool_limit: {{ .Values.litellm.general_settings.database_connection_pool_limit }}
      database_connection_timeout: {{ .Values.litellm.general_settings.database_connection_timeout }}
      allow_requests_on_db_unavailable: {{ .Values.litellm.general_settings.allow_requests_on_db_unavailable }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: litellm-deployment
  namespace: {{ .Release.Namespace }}
  labels:
    app: litellm
spec:
  selector:
    matchLabels:
      app: litellm
  template:
    metadata:
      labels:
        app: litellm
    spec:
      containers:
      - name: litellm
        image: ghcr.io/berriai/litellm:main-latest # it is recommended to fix a version generally
        env:
        - name: LITELLM_MASTER_KEY
          value: {{ .Values.litellm.general_settings.master_key }}
        - name: LITELLM_SALT_KEY
          value: {{ .Values.litellm.general_settings.salt_key }}
        - name: DATABASE_URL
          value: {{ .Values.litellm.general_settings.database_url }} #"postgresql://{{ .Values.postgres.db_user }}:{{ .Values.postgres.db_password }}@postgres.{{ .Release.Namespace }}.svc.cluster.local:5432/{{ .Values.postgres.db_name }}"
        - name: DATABASE_NAME
          value: {{ .Values.litellm.general_settings.database_name }} #{{ .Values.postgres.db_name }}
        - name: DATABASE_USER
          value: {{ .Values.litellm.general_settings.database_user }} #{{ .Values.postgres.db_user }}
        - name: DATABASE_PASSWORD
          value: {{ .Values.litellm.general_settings.database_password }} #{{ .Values.postgres.db_password }}
        - name: DATABASE_PORT
          value: "{{ .Values.litellm.general_settings.database_port }}"
        - name: STORE_MODEL_IN_DB
          value: "True"
        ports:
        - containerPort: 4000
        volumeMounts:
        - name: config-volume
          mountPath: /app/proxy_server_config.yaml
          subPath: config.yaml
        # envFrom:
        # - secretRef:
        #     name: litellm-secrets
      volumes:
        - name: config-volume
          configMap:
            name: litellm-config-file
---
apiVersion: v1
kind: Service
metadata:
  name: litellm-service
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: litellm
  ports:
    - protocol: TCP
      port: 4000
      targetPort: 4000
      nodePort: {{ .Values.litellm.service.node_port }}
  type: NodePort