apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-api-external
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: external-service
spec:
  type: NodePort
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: {{ .Values.external.api.nodePort | default 33000 }}
      protocol: TCP
      name: http
  selector:
    io.lago.service: {{ .Release.Name }}-api
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-front-external
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: external-service
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: {{ .Values.external.front.nodePort | default 30080 }}
      protocol: TCP
      name: http
  selector:
    io.lago.service: {{ .Release.Name }}-front
