apiVersion: v1
kind: Service
metadata:
  name: kalavai-gui-service
  namespace: {{ .Release.Namespace }}
spec:
  type: NodePort
  ports:
  - port: {{ .Values.deployment.internal_gui_port }}
    targetPort: {{ .Values.deployment.internal_gui_port }}
    nodePort: {{ .Values.service.frontend_nodePort }}
  - port: {{ .Values.deployment.internal_backend_port }}
    targetPort: {{ .Values.deployment.internal_backend_port }}
    nodePort: {{ .Values.service.backend_nodePort }}
  selector:
    app: kalavai-gui