image_tag: latest

deployment:
  bridge_api_url: ""
  bridge_api_port: ""
  access_key: ""
  internal_gui_port: 3000
  internal_backend_port: 8000
  internal_backend_host: "0.0.0.0"

service:
  backend_nodePort: 30008
  frontend_nodePort: 30009