apiVersion: v1
stringData:
  watcher_api_key: {{ .Values.bridge.watcherApiKey }}
  clickhouse_password: {{ .Values.clickhouse.password }}
kind: Secret
metadata:
  name: {{ .Release.Name }}-kalavai-api-secret
type: Opaque
immutable: true