---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.s3.secretName }}
stringData:
  accessKeyID: {{ .Values.s3.accessKeyID }}
  secretAccessKey: {{ .Values.s3.secretAccessKey }}
---
apiVersion: datashim.io/v1alpha1
kind: Dataset
metadata:
  name: {{ .Values.dataset.name }}
spec:
  local:
    type: {{ .Values.dataset.type }}
    secret-name: {{ .Values.s3.secretName }}
    endpoint: {{ .Values.s3.endpoint }}
    bucket: {{ .Values.s3.bucket }}
    readonly: {{ .Values.dataset.readonly }}

