releaseName:

forcedNamespace: null

bridge:
  replicas: 1
  nodeSelector: null
  labels:
    name: kalavai-api
  imageTag: latest
  enabled: true
  watcherApiUrl: localhost:30000
  watcherApiKey: api_key_here
  cpus: 0.33
  memory: 256Mi
  ringfenceNodeLabel: null
  ringfenceNodeLabelValue: null

  service:
    type: NodePort
